version: "3"
services:
  play:
    build: ./sbt
    container_name: play-vue
    volumes:
      - ..:/app
      - ./.ivy2:/root/.ivy2
      - ./.cache:/root/.cache
      - ./.sbt:/root/.sbt
    command: run

  nginx:
    build: ./nginx
    container_name: play-vue-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 18080:80
    depends_on:
      - play

networks:
  default:
    driver: bridge
